### PR TITLE
transport: cluster, conn, fixed PR #157 issues.

### LINKED ISSUE #163: cluster: address last minute review items from PR 157
https://github.com/mmatczuk/scylla-go-driver/pull/157

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #163

### CODE REVIEW

File: transport/cluster.go [hunk 1]
```diff
@@ -248,16 +248,15 @@ func (c *Cluster) loop() {
...
+			ticker = time.NewTimer(refreshInterval)
 		case <-c.reopenControlChan:
 			c.reopenControl()
 		case <-c.closeChan:
 			c.handleClose()
 			return
 		case <-ticker.C:
 			c.tryRefresh()
-			ticker.Reset(refreshInterval)
+			ticker = time.NewTimer(refreshInterval)
```
Comment (mmatczuk) [inline transport/cluster.go:259]: Use [Ticker](https://pkg.go.dev/time#Ticker) not here but instead of Timer.

Ticker != Timer

**Review by mmatczuk — CHANGES_REQUESTED** [review]
See comments inline.

**Review by mmatczuk — APPROVED** [review]
