### PR TITLE
transport: cluster, reopening control doesn't force close previous conn

### LINKED ISSUE #162: cluster: reopenControl try harder
The current code is very fast to close the current conn.

```
func (c *Cluster) reopenControl() {
	log.Printf("reopen control connection")
	c.control.Close()
	if err := c.NewControl(); err != nil {
		c.Close()
		log.Fatalf("failed to reopen control connection: %v", err)
	}
}
```

The flow should be:
- Try opening new connection if failed return error
- Replace connection and close the old one.
- log.Fatalf should not be here.

### PR DESCRIPTION
**Pull request by Michal-Leszczynski**
Fixes #162

### CODE REVIEW

File: transport/cluster.go [hunk 1]
```diff
@@ -264,28 +264,33 @@ func (c *Cluster) loop() {
...
 	log.Printf("cluster: reopen control connection")
-	c.control.Close()
-	if err := c.NewControl(); err != nil {
-		c.Close()
-		log.Fatalf("cluster: failed to reopen control connection: %v", err)
+	if control, err := c.NewControl(); err != nil {
+		go func() {
+			<-time.After(reopenControlInterval)
+			c.RequestReopenControl()
+		}()
```
Comment (mmatczuk) [inline transport/cluster.go:283]: use `time.AfterFunc`

**Comment by mmatczuk** [comment]
LGTM
